### ISSUE TITLE
Public client Id and the URI will risk app privacy

### ISSUE THREAD

**Issue by iggied** [HenrikJoreteg/github-secret-keeper#1]
So the only information required by a "misuser" is the URI with the public client Id, to masquerade as you. This information is easily accessible in the client web app for anyone to peek. I am unable to understand this architectural design in most of the modern web apps. Maybe I am missing something.

**Comment by HenrikJoreteg** [comment]
nope, the client ID is meant to be public. The security comes from the fact that after you re-direct to github, github will only redirect back to the registered app's url. So only the registered app can get the code required to ultimately fetch the token using the server in this repo. This is also why it's important that it's https all the way around.
